source 'https://rubygems.org'

gem 'rails', ">= 5.0.0"
gem 'mysql2'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'kaminari'
gem 'convergence'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'

group :development do
  gem 'spring'
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-livereload'
  gem 'capistrano', '~> 3.4.0', require: false
  gem 'capistrano3-unicorn', require: false
  gem 'capistrano-rails', require: false
  gem 'rvm1-capistrano3', require: nil
  gem 'capistrano-bundler', require: false
  gem 'capistrano-maintenance', github: 'capistrano/maintenance', require: false
end

group :test do
  gem 'rspec'
end

group :development, :test do
  gem 'puma'
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'guard'
  gem 'guard-rspec'
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'factory_girl_rails'
end
